export interface SiniestroParams {
  siniestro: number;
  ramo: Ramo;
}

export enum Ramo {
  hogar = 8,
  comercio = 9,
  comercio2 = 32,
  comercio3 = 34,
}

export enum TipoSiniestro {
  siniestrosComunitariosSinDañosEnViviendaAsegurada = 1,
  dañosPorAguaHogar = 2,
  incendioOExplosion = 3,
  roboEnViviendaAsegurada = 4,
  roturaEnCristales = 5,
  dañosElectricosPorSobretensionORayo = 6,
  actosVandalicos = 7,
  nieveVientoGranizoHumo = 8,
  impactoDeVehiculos = 9,
  extravioSustraccionLlavesOAperturaNoUrgenteDePuerta = 10,
  responsabilidadCivilFamiliar = 11,
  siniestrosConsorciables = 12,
  deterioroDeAlimentosEnCamarasFrigorificas = 13,
  reclamacionDaños = 14,
  otrosDañosAccidentales = 15,
  atracoFueraDeVivienda = 16,
  dañosABienesDepositadosEnHotelesAptos = 17,
  otrosMotivos = 18,
  solicitudServiciosUrgentes = 19,
  siniestrosComunitariosSinDañosEnComerciosAsegurado = 20,
  roboEnComercioAsegurado = 21,
  roturaDeRotulos = 22,
  nieveVientoOPedrisco = 23,
  responsabilidadCivilDerivadaDeLaActividad = 24,
  deterioroDeBienesRefrigerados = 25,
  roturaOAveriaDeMaquinariaOEquiposEletronicos = 26,
  expoliacionDeFondosDuranteSuTrasladoAEntidadBancaria = 27,
  orientacionJuridicaTelefonica = 28,
  defensaConsumidor = 29,
  defensaArrendador = 30,
  conflictosLaboralesLindesYDeComunidIrpfYPatrimonio = 31,
  servicioManitas = 32,
  asistenciaHogar = 33,
  peritacionAsistencia = 34,
  oQueiHome = 35,
  oQueiComerceAsistencia = 36,
  asistenciaComercio = 37,
  desperfectosPorRoboContinenteSinRoboContenido = 38,
  desperfectosPorRoboContinenteYRoboContenido = 39,
  roboContenido = 40,
  dañosPorAguaComercio = 41,
  expoliacionDeFondos = 42,
  agentesAtmosfericos = 43,
  sustitucionDeCerraduras = 44,
  roturaDeMaquinaria = 45,
  roturaEquiposElecctronicos = 46,
  derrameDeLiquidos = 47,
  deterioroDeJardines = 48,
  responsabilidadCivilDañosMateriales = 49,
  responsabilidadCivilLesiones = 50,
  responsabilidadCivilAutomocionDañosAVehiculos = 51,
  derrameDeVino = 52,
  dañosALosDepositos = 53,
  roturaDeEnvases = 54,
  derrameDeMaterialFundido = 55,
  recuperacionDeMaterialesFundidos = 56,
  dañosAObrasMenores = 57,
  asistenciaVip = 58,
  averiaDeElectrodomesticosODañosElectricos = 59,
}
